In [1]:
import pandas as pd
import numpy as np

from Algorithm import ProvenanceSearchValues_6_20220825 as ps
from Algorithm import LatticeTraversal_2_2022405 as lt


In [4]:
compas = pd.read_csv(r"../compas-scores.csv", index_col=False)
len(compas)

11757

In [5]:
compas.describe()

id           age  juv-fel-count  decile-score  \
count  11757.000000  11757.000000   11757.000000  11757.000000   
mean    5879.000000     35.143319       0.061580      4.371268   
std     3394.097892     12.022894       0.445328      2.877598   
min        1.000000     18.000000       0.000000     -1.000000   
25%     2940.000000     25.000000       0.000000      2.000000   
50%     5879.000000     32.000000       0.000000      4.000000   
75%     8818.000000     43.000000       0.000000      7.000000   
max    11757.000000     96.000000      20.000000     10.000000   

       juv-misd-count  juv-other-count  priors-count  days-b-screening-arrest  \
count    11757.000000     11757.000000  11757.000000             10577.000000   
mean         0.076040         0.093561      3.082164                -0.878037   
std          0.449757         0.472003      4.687410                72.889298   
min          0.000000         0.000000      0.000000              -597.000000   
25%          0.000000         0.000000      0.000000                -1.000000   
50%          0.000000         0.000000      1.000000                -1.000000   
75%          0.000000         0.000000      4.000000                -1.000000   
max         13.000000        17.000000     43.000000              1057.000000   

       c-days-from-compas      is-recid  num-r-cases  r-days-from-arrest  \
count        11015.000000  11757.000000          0.0         2460.000000   
mean            63.587653      0.253806          NaN           20.410569   
std            341.899711      0.558324          NaN           74.354840   
min              0.000000     -1.000000          NaN           -1.000000   
25%              1.000000      0.000000          NaN            0.000000   
50%              1.000000      0.000000          NaN            0.000000   
75%              2.000000      1.000000          NaN            1.000000   
max           9485.000000      1.000000          NaN          993.000000   

       is-violent-recid  num-vr-cases  v-decile-score  decile-score.1  
count      11757.000000           0.0    11757.000000    11757.000000  
mean           0.075019           NaN        3.571489        4.371268  
std            0.263433           NaN        2.500479        2.877598  
min            0.000000           NaN       -1.000000       -1.000000  
25%            0.000000           NaN        1.000000        2.000000  
50%            0.000000           NaN        3.000000        4.000000  
75%            0.000000           NaN        5.000000        7.000000  
max            1.000000           NaN       10.000000       10.000000

In [ ]:
lst = compas["juv-fel-count"].unique()
lst.sort()
print(lst)
# lst2 = list(range(1, 100))
# print([x for x in lst2 if x not in lst])
# # without 69, 71


lst = compas["decile-score"].unique()
lst.sort()
print(lst)


# make 10K data

In [8]:
juv_lst = [ 0,  1,  2,  3,  4,  5,  6,  8,  9, 10, 13, 20]
for i in juv_lst:
    print(len(compas[compas["juv-fel-count"] == i]))

11334
280
80
30
16
8
2
2
1
2
1
1


In [9]:
dec_lst = [-1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]
for i in dec_lst:
    print(len(compas[compas["decile-score"] == i]))

15
2577
1572
1259
1199
1034
993
900
796
802
610


In [10]:
def remove_hours(hours, sam, compas):
    print(len(compas))
    a1 = compas[compas['decile-score'] == hours].sample(sam)
    print(len(a1))
    compas = compas[~compas.index.isin(a1.index)]
    print(len(compas))
    return compas


In [11]:
print(len(compas))
compas = remove_hours(1, 1000, compas)
print(len(compas))

11757
11757
1000
10757
10757


In [12]:
print(len(compas))
compas = remove_hours(2, 500, compas)
print(len(compas))

10757
10757
500
10257
10257


In [13]:
print(len(compas))
compas = remove_hours(3, 257, compas)
print(len(compas))

10257
10257
257
10000
10000


In [14]:
lst = compas["juv-fel-count"].unique()
lst.sort()
print(lst)

lst = compas["decile-score"].unique()
lst.sort()
print(lst)


[ 0  1  2  3  4  5  6  8  9 10 13 20]
[-1  1  2  3  4  5  6  7  8  9 10]


In [15]:
compas.to_csv("compas_10k.csv", index=False)

# make 5k data

In [17]:
dec_lst = [-1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]
for i in dec_lst:
    print(len(compas[compas["decile-score"] == i]))

15
1577
1072
1002
1199
1034
993
900
796
802
610


In [18]:
print(len(compas))
compas = remove_hours(1, 1000, compas)
print(len(compas))

10000
10000
1000
9000
9000


In [19]:
print(len(compas))
compas = remove_hours(2, 1000, compas)
print(len(compas))

9000
9000
1000
8000
8000


In [20]:
print(len(compas))
compas = remove_hours(3, 1000, compas)
print(len(compas))

8000
8000
1000
7000
7000


In [21]:
print(len(compas))
compas = remove_hours(4, 1000, compas)
print(len(compas))

7000
7000
1000
6000
6000


In [22]:
print(len(compas))
compas = remove_hours(5, 1000, compas)
print(len(compas))

6000
6000
1000
5000
5000


In [23]:
lst = compas["juv-fel-count"].unique()
lst.sort()
print(lst)

lst = compas["decile-score"].unique()
lst.sort()
print(lst)



[ 0  1  2  3  4  5  6  8 10 13 20]
[-1  1  2  3  4  5  6  7  8  9 10]


In [ ]:
compas.to_csv("compas_5k.csv", index=False)


In [38]:
compas = pd.read_csv("compas_5k.csv", index_col=False)
lst = compas["juv-fel-count"].unique()
lst.sort()
print(lst)

lst = compas["decile-score"].unique()
lst.sort()
print(lst)


[ 0  1  2  3  4  5  6  8 10 13 20]
[-1  1  2  3  4  5  6  7  8  9 10]


In [39]:
compas1 = compas[compas["juv-fel-count"] <= 4] # size = 20
print(len(compas1))
compas2 = compas1[compas1["decile-score"] >= 8] # size = 5
print(len(compas2))
compas3 = compas2[compas2["c-charge-degree"] == "O"]  # size = 30
print(len(compas3))

AA = compas3[compas3["race"] == "African-American"]
print(len(AA))
female = compas3[compas3["sex"]=="Male"]
print(len(female))


4986
2196
115
88
92


# make 2.5 k data

In [25]:
dec_lst = [-1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]
for i in dec_lst:
    print(len(compas[compas["decile-score"] == i]))

15
577
72
2
199
34
993
900
796
802
610


In [26]:
compas = compas[compas['decile-score'] >= 7]
len(compas)

3108

In [27]:
print(len(compas))
compas = remove_hours(7, 608, compas)
print(len(compas))

3108
3108
608
2500
2500


In [28]:
compas.to_csv("compas_2p5k.csv")

# make 2k data

In [41]:
compas_2p5k = pd.read_csv("compas_2p5k.csv", index_col=False)


dec_lst = [-1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]
for i in dec_lst:
    print(len(compas[compas["decile-score"] == i]))

15
577
72
2
199
34
993
900
796
802
610


In [42]:
print(len(compas))
compas = remove_hours(9, 500, compas)
print(len(compas))

5000
5000
500
4500
4500


In [43]:
compas.to_csv("compas_2k.csv", index=False)


In [ ]:

compas = pd.read_csv("compas_2k.csv", index_col=False)

lst = compas["juv-fel-count"].unique()
lst.sort()
print(lst)

lst = compas["decile-score"].unique()
lst.sort()
print(lst)

compas1 = compas[compas["juv-fel-count"] <= 4] # size = 20
print(len(compas1))
compas2 = compas1[compas1["decile-score"] >= 8] # size = 5
print(len(compas2))
compas3 = compas2[compas2["c-charge-degree"] == "O"]  # size = 30
print(len(compas3))

AA = compas3[compas3["race"] == "African-American"]
print(len(AA))
female = compas3[compas3["sex"]=="Male"]
print(len(female))



# make 1k data

In [32]:
dec_lst = [-1,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]
for i in dec_lst:
    print(len(compas[compas["decile-score"] == i]))

0
0
0
0
0
0
0
292
796
302
610


In [33]:
print(len(compas))
compas = remove_hours(8, 500, compas)
print(len(compas))

2000
2000
500
1500
1500


In [34]:
print(len(compas))
compas = remove_hours(10, 400, compas)
print(len(compas))

1500
1500
400
1100
1100


In [35]:
print(len(compas))
compas = remove_hours(7, 100, compas)
print(len(compas))

1100
1100
100
1000
1000


In [36]:
compas.to_csv("compas_1k.csv", index=False)